apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: flights-app-templates
  description: Flight App Templates and Components
spec:
  targets:
    - ./template.yaml
    - ./flights-app/catalog-info.yaml