apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitops-flights-deploy
  title: Deploy Flights App via GitOps
  description: Fetch flights app manifests and create a GitOps repository
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Configuration
      required:
        - name
        - repoUrl
      properties:
        name:
          title: Application Name
          type: string
          description: Name for your GitOps repository
          default: flights-app
        repoUrl:
          title: Target GitOps Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    # Fetch the flights-app manifests from source repo
    - id: fetch
      name: Fetch Flights App Manifests
      action: fetch:plain
      input:
        url: https://github.com/stuntman86/flights-app/tree/main/flights-app

    # Publish to new GitHub repository
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: GitOps repository for ${{ parameters.name }} - monitored by ArgoCD
        defaultBranch: main

  output:
    links:
      - title: GitOps Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: View Files
        url: ${{ steps.publish.output.remoteUrl }}/tree/main
